name: scrape

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python amazon_deals_rss.py

      - name: Commit and push rss.xml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
