name: Scrape Amazon Deals & Update RSS Feed

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:       # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python amazon_deals_rss.py

      - name: Commit RSS Feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          # Replace repo URL to include token
          GIT_ASKPASS: echo "${GH_PAT}"


